sudo: required

language: python

python:
  - 3.5
  - 3.6

cache: pip

install:
  - pip install -r requirements.txt

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

before_install:
  # install updated version of docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version
  # build docker image
  - docker build -t $DOCKER_USERNAME/universitybot .
  # - docker run $DOCKER_USERNAME/universitybot
  # - docker ps -a
  # - docker stats --no-stream

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/universitybot;
    fi

script:
  - nosetest