sudo: required

language: python

python:
  - 3.5
  - 3.6

cache: pip

install:
  - pip install -r requirements.txt

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

before_install:
  # install updated version of docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - docker --version
  # build docker image
  - docker build -t $DOCKER_USERNAME/universitybot .
  # run docker container
  - mv ./conf/conf.example.json ./conf/conf.json
  - sed -i "/        \"token\":\"\",/c\        \"token\":\"$TELEGRAM_STAGINGBOT_TOKEN\"," ./conf/conf.json
  - pwd
  - docker run -d $DOCKER_USERNAME/universitybot --volume=$TRAVIS_BUILD_DIR/conf:/opt/UniversityBot/conf
  - docker ps -a
  - docker stats --no-stream

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/universitybot;
    fi

script:
  - nosetests